import {
  ApertureIcon,
  CalendarDaysIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  CircleHelpIcon,
  CircleIcon,
  CircleMinusIcon,
  CirclePlusIcon,
  Clock1Icon,
  EllipsisIcon,
  Home,
  ImageIcon,
  LoaderIcon,
  Package,
  Settings2,
  ShoppingCart,
  SlashIcon,
  Trash2Icon,
  type LucideIcon,
} from "lucide-react";

export type IconType = LucideIcon;

export const Icons = {
  package: Package,
  home: Home,
  shoppingCart: ShoppingCart,
  circlePlus: CirclePlusIcon,
  circleMinus: CircleMinusIcon,
  help: CircleHelpIcon,
  slash: SlashIcon,
  loader: LoaderIcon,
  check: CheckIcon,
  arrowDown: ChevronDownIcon,
  calendar: CalendarDaysIcon,
  horizontalEllipsis: EllipsisIcon,
  delete: Trash2Icon,
  settings: Settings2,
  circle: CircleIcon,
  clock: Clock1Icon,
  checkCircle: CheckCircle2Icon,
  chevronsUpDown: ChevronsUpDownIcon,
  logo: ApertureIcon,
  image: ImageIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
};
