"use client";

import {
  ApertureIcon,
  AtSignIcon,
  CalendarDaysIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  CircleHelpIcon,
  CircleIcon,
  CircleMinusIcon,
  CirclePlusIcon,
  Clock1Icon,
  CogIcon,
  CrownIcon,
  EllipsisIcon,
  EllipsisVertical,
  EyeIcon,
  EyeOffIcon,
  Home,
  ImageIcon,
  LayersIcon,
  LoaderIcon,
  LogOutIcon,
  MoveUpRight,
  Package,
  PanelLeftIcon,
  PenLineIcon,
  ReceiptTextIcon,
  Settings2,
  ShieldAlertIcon,
  ShoppingBagIcon,
  ShoppingCart,
  SlashIcon,
  Trash2Icon,
  UserMinusIcon,
  UserPlusIcon,
  XIcon,
  type LucideIcon,
} from "lucide-react";

import { ComponentType, SVGProps } from "react";

export type IconType = LucideIcon | ComponentType<SVGProps<SVGSVGElement>>;

export const Icons = {
  package: Package,
  home: Home,
  shoppingCart: ShoppingCart,
  circlePlus: CirclePlusIcon,
  circleMinus: CircleMinusIcon,
  help: CircleHelpIcon,
  slash: SlashIcon,
  loader: LoaderIcon,
  check: CheckIcon,
  arrowDown: ChevronDownIcon,
  calendar: CalendarDaysIcon,
  horizontalEllipsis: EllipsisIcon,
  delete: Trash2Icon,
  settings: Settings2,
  circle: CircleIcon,
  clock: Clock1Icon,
  checkCircle: CheckCircle2Icon,
  chevronsUpDown: ChevronsUpDownIcon,
  logo: ApertureIcon,
  image: ImageIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  verticalEllipsis: EllipsisVertical,
  moveUpRight: MoveUpRight,
  x: XIcon,
  update: PenLineIcon,
  signOut: LogOutIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  alert: ShieldAlertIcon,
  cog: CogIcon,
  receipt: ReceiptTextIcon,
  panelLeft: PanelLeftIcon,
  atSign: AtSignIcon,
  bag: ShoppingBagIcon,
  layers: LayersIcon,
  userPlus: UserPlusIcon,
  userMinus: UserMinusIcon,
  crown: CrownIcon
};
